# server/mcp_server.py
"""
MCP FastAPI server exposing three tools:
- /mcp/tool/flights.list?region=<region>
- /mcp/tool/flights.get?identifier=<callsign|icao24>
- /mcp/tool/alerts.list
Also exposes /mcp/manifest for agent registration.
"""

from fastapi import FastAPI, HTTPException, Query
from typing import List, Dict
import time
from . import db

app = FastAPI(title="Airspace MCP Server")

@app.get("/mcp/tool/flights.list")
def flights_list(region: str = Query("region1")):
    """
    Return latest snapshot for region.
    """
    snap = db.load_flights_for_region(region)
    return {
        "region": snap.get("region", region),
        "last_updated": snap.get("last_updated"),
        "flights": snap.get("flights", []),
        "count": len(snap.get("flights", []))
    }

@app.get("/mcp/tool/flights.get")
def flights_get(identifier: str = Query(...)):
    """
    Get a single flight record by callsign or icao24.
    """
    flight = db.get_flight_by_identifier(identifier)
    if flight:
        return flight
    raise HTTPException(status_code=404, detail="Flight not found")

@app.get("/mcp/tool/alerts.list")
def alerts_list(active_only: bool = True):
    """
    Return alerts stored by system (or generated by n8n). If none exist, compute basic alerts on-the-fly.
    """
    alerts = db.load_alerts()
    if alerts:
        if active_only:
            return [a for a in alerts if a.get("active", True)]
        return alerts

    # compute simple alerts on-the-fly from snapshot
    snap = db.load_flights_for_region("region1")
    computed = []
    for f in snap.get("flights", []):
        if f.get("on_ground"):
            continue
        velocity = f.get("velocity_mps") or 0
        altitude = f.get("geo_altitude") or f.get("baro_altitude") or 0
        vr = abs(f.get("vertical_rate_mps") or 0)
        anomalies = []
        if velocity < 50 and altitude > 5000:
            anomalies.append("Low speed at high altitude")
        if vr > 20:
            anomalies.append(f"High vertical rate: {vr} m/s")
        if anomalies:
            computed.append({
                "icao24": f.get("icao24"),
                "callsign": f.get("callsign"),
                "anomalies": anomalies,
                "created_at": int(time.time()),
                "active": True
            })
    return computed

@app.get("/mcp/manifest")
def manifest():
    """
    Return minimal MCP manifest describing the available tools.
    """
    return {
        "service": "airspace-mcp",
        "tools": [
            {"name": "flights.list", "description": "Return latest flights snapshot for a region", "endpoint": "/mcp/tool/flights.list?region=<region>"},
            {"name": "flights.get", "description": "Return latest flight by callsign or icao24", "endpoint": "/mcp/tool/flights.get?identifier=<value>"},
            {"name": "alerts.list", "description": "Return current alerts", "endpoint": "/mcp/tool/alerts.list"}
        ],
        "health": "ok"
    }
